config/routes.rb
ArmyBuilder::Application.routes.draw do
  resources :armies

  resources :army_units

  resources :unit_types

  resources :units

  resources :factions

  root 'welcome#index'

  

end

app/models/army_unit.rb
class ArmyUnit < ActiveRecord::Base
  belongs_to :unit
  belongs_to :army
end

app/controllers/army_units_controller.rb
class ArmyUnitsController < ApplicationController
  before_action :set_army_unit, only: [:show, :edit, :update, :destroy]

  # GET /army_units
  # GET /army_units.json
  def index
    @army_units = ArmyUnit.all
  end

  # GET /army_units/1
  # GET /army_units/1.json
  def show
  end

  # GET /army_units/new
  def new
    @army_unit = ArmyUnit.new
  end

  # GET /army_units/1/edit
  def edit
  end

  # POST /army_units
  # POST /army_units.json
  def create
    @army_unit = ArmyUnit.new(army_unit_params)

    respond_to do |format|
      if @army_unit.save
        format.html { redirect_to @army_unit, notice: 'Army unit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @army_unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @army_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /army_units/1
  # PATCH/PUT /army_units/1.json
  def update
    respond_to do |format|
      if @army_unit.update(army_unit_params)
        format.html { redirect_to @army_unit, notice: 'Army unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @army_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /army_units/1
  # DELETE /army_units/1.json
  def destroy
    @army_unit.destroy
    respond_to do |format|
      format.html { redirect_to army_units_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_army_unit
      @army_unit = ArmyUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def army_unit_params
      params.require(:army_unit).permit(:unit_id, :army_id)
    end
end

app/helpers/army_units_helper.rb
module ArmyUnitsHelper
end

app/views/army_units/_form.html.erb
<%= form_for(@army_unit) do |f| %>
  <% if @army_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@army_unit.errors.count, "error") %> prohibited this army_unit from being saved:</h2>

      <ul>
      <% @army_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit %><br>
    <%= f.select :unit_id, options_for_select(Unit.all.collect { |u| [u.name, u.id] }, @army_unit.unit_id) %>
  </div>
  <div class="field">
    <%= f.label :army %><br>
    <%= f.select :army_id, options_for_select(Army.all.collect { |a| [a.name, a.id] }, @army_unit.army_id) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/army_units/edit.html.erb
<h1>Editing army_unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @army_unit %> |
<%= link_to 'Back', army_units_path %>

app/views/army_units/index.html.erb
<h1>Listing army_units</h1>

<table>
  <thead>
    <tr>
      <th>Unit</th>
      <th>Army</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @army_units.each do |army_unit| %>
      <tr>
        <td><%= army_unit.unit.name %></td>
        <td><%= army_unit.army.name %></td>
        <td><%= link_to 'Show', army_unit %></td>
        <td><%= link_to 'Edit', edit_army_unit_path(army_unit) %></td>
        <td><%= link_to 'Destroy', army_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Army unit', new_army_unit_path %>

app/views/army_units/new.html.erb
<h1>New army_unit</h1>

<%= render 'form' %>

<%= link_to 'Back', army_units_path %>

app/views/army_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unit:</strong>
  <%= @army_unit.unit %>
</p>

<p>
  <strong>Army:</strong>
  <%= @army_unit.army %>
</p>

<%= link_to 'Edit', edit_army_unit_path(@army_unit) %> |
<%= link_to 'Back', army_units_path %>