config/routes.rb
ArmyBuilder::Application.routes.draw do
  resources :armies

  resources :army_units

  resources :unit_types

  resources :units

  resources :factions

  root 'welcome#index'

  

end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  before_action :set_faction, only: [:show, :edit, :update, :destroy]

  # GET /factions
  # GET /factions.json
  def index
    @factions = Faction.all
  end

  # GET /factions/1
  # GET /factions/1.json
  def show
  end

  # GET /factions/new
  def new
    @faction = Faction.new
  end

  # GET /factions/1/edit
  def edit
  end

  # POST /factions
  # POST /factions.json
  def create
    @faction = Faction.new(faction_params)

    respond_to do |format|
      if @faction.save
        format.html { redirect_to @faction, notice: 'Faction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @faction }
      else
        format.html { render action: 'new' }
        format.json { render json: @faction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factions/1
  # PATCH/PUT /factions/1.json
  def update
    respond_to do |format|
      if @faction.update(faction_params)
        format.html { redirect_to @faction, notice: 'Faction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @faction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factions/1
  # DELETE /factions/1.json
  def destroy
    @faction.destroy
    respond_to do |format|
      format.html { redirect_to factions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faction
      @faction = Faction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faction_params
      params.require(:faction).permit(:name)
    end
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/views/factions/_form.html.erb
<%= form_for(@faction) do |f| %>
  <% if @faction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faction.errors.count, "error") %> prohibited this faction from being saved:</h2>

      <ul>
      <% @faction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factions/edit.html.erb
<h1>Editing faction</h1>

<%= render 'form' %>

<%= link_to 'Show', @faction %> |
<%= link_to 'Back', factions_path %>

app/views/factions/index.html.erb
<h1>Listing factions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @factions.each do |faction| %>
      <tr>
        <td><%= faction.name %></td>
        <td><%= link_to 'Show', faction %></td>
        <td><%= link_to 'Edit', edit_faction_path(faction) %></td>
        <td><%= link_to 'Destroy', faction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faction', new_faction_path %>

app/views/factions/new.html.erb
<h1>New faction</h1>

<%= render 'form' %>

<%= link_to 'Back', factions_path %>

app/views/factions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @faction.name %>
</p>

<%= link_to 'Edit', edit_faction_path(@faction) %> |
<%= link_to 'Back', factions_path %>