config/routes.rb
ArmyBuilder::Application.routes.draw do
  resources :armies

  resources :army_units

  resources :unit_types

  resources :units

  resources :factions

  root 'welcome#index'

  

end

app/models/army.rb
class Army < ActiveRecord::Base
  
  def to_s
    name
  end
end

app/controllers/armies_controller.rb
class ArmiesController < ApplicationController
  before_action :set_army, only: [:show, :edit, :update, :destroy]

  # GET /armies
  # GET /armies.json
  def index
    @armies = Army.all
  end

  # GET /armies/1
  # GET /armies/1.json
  def show
  end

  # GET /armies/new
  def new
    @army = Army.new
  end

  # GET /armies/1/edit
  def edit
  end

  # POST /armies
  # POST /armies.json
  def create
    @army = Army.new(army_params)

    respond_to do |format|
      if @army.save
        format.html { redirect_to @army, notice: 'Army was successfully created.' }
        format.json { render action: 'show', status: :created, location: @army }
      else
        format.html { render action: 'new' }
        format.json { render json: @army.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /armies/1
  # PATCH/PUT /armies/1.json
  def update
    respond_to do |format|
      if @army.update(army_params)
        format.html { redirect_to @army, notice: 'Army was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @army.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /armies/1
  # DELETE /armies/1.json
  def destroy
    @army.destroy
    respond_to do |format|
      format.html { redirect_to armies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_army
      @army = Army.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def army_params
      params.require(:army).permit(:name)
    end
end

app/helpers/armies_helper.rb
module ArmiesHelper
end

app/views/armies/_form.html.erb
<%= form_for(@army) do |f| %>
  <% if @army.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@army.errors.count, "error") %> prohibited this army from being saved:</h2>

      <ul>
      <% @army.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/armies/edit.html.erb
<h1>Editing army</h1>

<%= render 'form' %>

<%= link_to 'Show', @army %> |
<%= link_to 'Back', armies_path %>

app/views/armies/index.html.erb
<h1>Listing armies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @armies.each do |army| %>
      <tr>
        <td><%= army.name %></td>
        <td><%= link_to 'Show', army %></td>
        <td><%= link_to 'Edit', edit_army_path(army) %></td>
        <td><%= link_to 'Destroy', army, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Army', new_army_path %>

app/views/armies/new.html.erb
<h1>New army</h1>

<%= render 'form' %>

<%= link_to 'Back', armies_path %>

app/views/armies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @army.name %>
</p>

<%= link_to 'Edit', edit_army_path(@army) %> |
<%= link_to 'Back', armies_path %>