config/routes.rb
ArmyBuilder::Application.routes.draw do
  resources :armies

  resources :army_units

  resources :unit_types

  resources :units

  resources :factions

  root 'welcome#index'

  

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates_presence_of :name, :base_cost

  belongs_to :faction
  belongs_to :unit_type

  def to_s
    name
  end
end

app/models/unit_type.rb
class UnitType < ActiveRecord::Base
  has_many :units
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :description, :base_cost, :unit_type_id, :faction_id, :model_count)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :base_cost %><br>
    <%= f.number_field :base_cost %>
  </div>
  <div class="field">
    <%= f.label :unit_type %><br>
    <%= f.select :unit_type_id, options_for_select(UnitType.all.collect { |ut| [ut.name, ut.id] }, @unit.unit_type_id) %>
  </div>
  <div class="field">
    <%= f.label :faction_id %><br>
    <%= f.select :faction_id, options_for_select(Faction.all.collect { |f| [f.name, f.id] }, @unit.faction_id) %>
  </div>
  <div class="field">
    <%= f.label :model_count %><br>
    <%= f.number_field :model_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Base cost</th>
      <th>Unit type</th>
      <th>Faction</th>
      <th>Model count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.base_cost %></td>
        <td><%= unit.unit_type ? unit.unit_type.name : '' %></td>
        <td><%= unit.faction ? unit.faction.name : '' %></td>
        <td><%= unit.model_count %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @unit.description %>
</p>

<p>
  <strong>Base cost:</strong>
  <%= @unit.base_cost %>
</p>

<p>
  <strong>Unit type:</strong>
  <%= @unit.unit_type_id %>
</p>

<p>
  <strong>Faction:</strong>
  <%= @unit.faction_id %>
</p>

<p>
  <strong>Model count:</strong>
  <%= @unit.model_count %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>